/* Step 4 */
DROP TABLE IF EXISTS games;

CREATE TABLE games (
	GameID INTEGER(4) AUTO_INCREMENT PRIMARY KEY,
	GameDate TIMESTAMP,
	HomeTeamID INTEGER(4) NOT NULL,
	VisitorTeamID INTEGER(4) NOT NULL,
	CONSTRAINT fk_HomeID FOREIGN KEY(HomeTeamID) REFERENCES teams (teamID),
	CONSTRAINT fk_VistorID FOREIGN KEY(VisitorTeamID) REFERENCES teams (teamID)
	);

